subnets={
    subnet1={
        name="subnetamit1"
        resource_group_name="rg-amit1"
        virtual_network_name="vnet-amit1"
        address_prefixes=["10.124.1.0/26"]
    }
    subnet2={
        name="subnetamit2"
        resource_group_name="rg-amit1"
        virtual_network_name="vnet-amit1"
        address_prefixes=["10.124.2.0/26"]
    }
    subnet3={
        name="subnetamit3"
        resource_group_name="rg-amit1"
        virtual_network_name="vnet-amit1"
        address_prefixes=["10.124.3.0/26"]
    }
}